services:
  - type: web
    name: telegram-bot
    env: docker
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: OPENAI_API_KEY
        value: ""
      - key: TELEGRAM_BOT_TOKEN
        value: ""
      - key: WEBHOOK_URL
        value: "https://telegram-bot-yxmt.onrender.com/webhook"
      - key: PORT
        value: "8080"

